version: '3'

services:
  db:
    container_name: demo.db
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    container_name: demo.web
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "9999:8000"
    depends_on:
      - db
  app:
    container_name: demo.app
    build:
      context: ./docker/python
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
        - "8080:8000"
    tty: true #　what's this!
    stdin_open: true #　what's this!
    depends_on:
      - db