version: '3'

services:
  
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql
    environment:
     MYSQL_ROOT_PASSWORD: root